konrad/atmosphere.py
konrad/core.py
konrad/utils.py

Move the complete model control to `RCE.run()`. The `Atmosphere` class is now only used to represent the atmospheric state.

Restructure model core

---

konrad/cloud.py

Use the size of the height array that is passed to the derived cloud
classes to determine the number of full levels that is used to
initalize the parent class.
The actual changes are a bit hidden between reformatting, sorry for that.
Essentially I only changed those two lines:
https://github.com/lkluft/konrad/blob/7d417ff805a3261c261d5ae2aee0127a5eab541e/konrad/cloud.py#L164
https://github.com/lkluft/konrad/blob/7d417ff805a3261c261d5ae2aee0127a5eab541e/konrad/cloud.py#L230

Fix value of `numlevels` for derived cloud classes.

---

konrad/radiation/rrtmg.py
tutorials/radiation_solver.ipynb
tutorials/simple_rce.ipynb
tutorials/venus_rce.ipynb

This PR fixes runs without McICA.
I got an exception when trying to run `konrad` with `mcica=False` because `_cloud_ice_properties` was not set. I guess it is fine to set it always, for ne non-McICA cases it should simply be ignored?

Fix non-McICA runs

---

.zenodo.json

This PR is supposed to add some metadata to Zenodo that cannot be inferred from the GitHub release alone. The approach is not really documented and hard to test as we need a release.
We could just merge this and see what happens in the next release 😉 
If you have anything to add (ORCID ID?) let me know ☺️

Add Zenodo metadata JSON file.

---

konrad/component.py
konrad/humidity/__init__.py
konrad/netcdf.py

Model components are now stored in the netCDF output regardless of their
number of attributes and variables. This ensures that at least their
classname is saved for documentation.

Write all components to netCDF file

---

konrad/humidity/stratosphere.py

Maybe it would also be worth making a similar one that could be used with your UTH peak and only prevents an increase in vmr with height above the convective top...

Include class to stop h2o increasing with altitude

---

docs/source/konrad.radiation.rst
konrad/atmosphere.py
konrad/constants.py
konrad/convection.py
konrad/lapserate.py
konrad/radiation/__init__.py
konrad/radiation/common.py
konrad/radiation/radiation.py
konrad/upwelling.py

This PR:
* Add a method to calculate the water-vapor-dependent specific isobaric heat capacity of the atmosphere
* Calculate the radiative heating tendency from from the radiative fluxes returned by RRTMG. This removes a bias in the equilibrium state, which was presumably introduced by a mismatch in the treatment of vertical coordinates

Calculate moist heat capacity and heating rates

---

konrad/cloud.py
konrad/convection.py
konrad/upwelling.py

It was already mostly as we want it. Good work by our previous selves :)
The reason for specifying the coupling level when the cloud is initialised:
The presence of a high cloud might 'mess up' convection for the first few iterations, and if the norm level is not specified it is taken as the convective top of the first iteration. This may then lead to a coupling of the high cloud to a level that is not where we want it to be.

Very small changes to high cloud class and coupling

---

docs/source/konrad.convection.rst
konrad/convection.py
konrad/core.py

This PR satisfies #80 and undoes most of PR #68, so the convective adjustment should work as before now (ie not taking into account latent heat in the energy balance). The only thing I left was the function to copy the atmosphere, because this may be useful for other things too. If at some point we decide we do want to include humidity changes in the energy considerations for the convective adjustment or just make another check that they are not important, we can always revert these reverted commits again :)

Undo things - do not include latent heat in convective adjustment

---

docs/source/konrad.utils.rst
konrad/atmosphere.py
konrad/humidity/relative_humidity.py
konrad/test/test_atmosphere.py
konrad/utils.py

This PR
* fixes the scaling of the upper-tropospheric UTH peak (``FixedUTH``, ``CoupledUTH``)
* simplifies the generation of pressure grids by using an analytical formula and less free parameters
The changes lead to the following API changes:
The function ``get_pressure_grids`` no longer supports the ``stop`` and ``squeeze`` arguments. The top-level pressure is now fixed to 1 Pa and a constant "default squeezing" is applied.

Revise functions

---

konrad/utils.py

It is now possible to set both the surface and the top level pressure for the quadratic pressure grid function.
As long as we do not want to change the strength of the "squeeze", the functions ``get_squeezable_pgrid`` and ``get_quadratic_pgrid`` should now be equivalent.

Enhance pressure grid creation

---

konrad/component.py

Importing abstract meta classes from ``collections`` instead of
``collections.abc`` is no longer supported in Python >=3.8.

Fix import of abstract meta class from collections

---

konrad/component.py

The method ``__getattr__``now raises a proper ``AttributeError``
when an attribute cannot be found. This fixes the pickle-ability of
component objects (needed for multiprocessing).

Fix attribute getter for model components

---

konrad/radiation/radiation.py

The heat capacity for dry air is used to convert radiative fluxes into
heating rates. This is consistent with the approach done in the
convective adjustment: The choice of the heat capacity does not affect
the equilibrium state as long as it is consistent for radiation and
convection.

Use dry heat capacity to calculate heating rates

---

.flake8
.github/workflows/python-publish.yml
setup.py

This PR:
* Adds a more merciful `flake8` configuration (consistent with [black](https://github.com/psf/black))
* Makes the automated PyPI release more robust
* Removes outdated/superfluous entries in the `setup.py`

Clean setup

---

konrad/humidity/__init__.py
konrad/humidity/relative_humidity.py
konrad/humidity/stratosphere.py

This PR:
* Adds the class `CacheFromAtmosphere` to calculate and store the initial relative humidity profile
* Removes the `NoCoupling` stratospheric coupling as it did not work as expected

Revise humidity models

---

konrad/core.py
konrad/radiation/radiation.py
konrad/radiation/rrtmg.py

Avoid confusion about the solar constant and zenith angle for radiative flux calculations outside of konrad.

Move diurnal_cycle specification

---

konrad/radiation/rrtmg.py

This is a minor enhancement for radiative transfer simulations at high temperatures. As the water-vapor mixing-ratio can exceed a couple of percent it is cleaner to scale the dry mixing ratios of all other gases accordingly. This prevents having more than `1` atmosphere in total.

Scale dry-air mixing-ratios with water content

---

konrad/constants.py
konrad/convection.py
konrad/core.py
konrad/surface.py

Combined surface classes, allowing a sink of energy to be added also in the fixed surface temperature case. Added an option to adjust the atmospheric CO2, so that equilibrium can be achieved quickly for a set-up with fixed surface temperature, following Romps 2020 "Climate sensitivity and the direct effect of carbon dioxide in a limited-area cloud-resolving model".

Adjust co2

---

konrad/atmosphere.py
konrad/ozone.py

This PR:
* Adds an `interpolate` keyword to enable a smoother cold-point detection
* Allows the user to choose between `convetive_top` and `cold_point` coupling to normalize the ozone profile

Add coldpoint interpolation

---

environment.yml
konrad/atmosphere.py
konrad/constants.py
konrad/radiation/__init__.py
konrad/radiation/arts.py
konrad/radiation/rrtmg.py
setup.py

This PR:
* adds a new radiation class ``ARTS``, which allows the user to run line-by-line longwave radiation
* reverts the scaling of VMRs with the water vapor conent for RRTMG. This is taken into account internally

Add ARTS class to run line-by-line LW radiation

---

.github/workflows/build-test.yml

The new build command should be more robust. In addition, it is closer
to the acatual command that users would use on their system.

Update the MacOS test build

---

.github/workflows/build-test.yml
.readthedocs.yml
setup.py

This PR:
* Adds the Python 3.8 classifier
* Enables automated testing for Python 3.8
* Builds the documentation on Python 3.7 instead of 3.6

Add Python 3.8 support

---

.gitattributes
.gitignore

This PR:
* makes git ignore the sphinx build directory
* prevents git from diffing Jupyter notebooks (they are treated like binary files)

Improve config

---

konrad/netcdf.py

This PR:
* Enables compression for netCDF files
* Stores `double` variables in single precision
In total, both measures reduce the file size by about 70%.

Optimize netCDF output

---

konrad/netcdf.py

The old implementation lead to an error when determining the str type:
NumPy adds the byte length of strings to the dtype name (e.g. "str320").
This causes the netCDF library to crash.

Fix data type check for strings when writing netCDF

---

konrad/core.py
konrad/surface.py

- Change the inheritance of FixedTemperature to Surface and not SlabSurface (there was no apparent reason for having in inheriting from SlabSurface as the new attribute of SlabSurface are not used in FixedTemperature)
- Update/change docstrings in Surface and Core.
- Make the from_netcdf method read all parameters for the class, and add a overloading method in SlabOcean for the new parameters.

Improve Surface documentation

---

docs/source/_templates/autosummary/class.rst
docs/source/index.rst
konrad/atmosphere.py
konrad/component.py
konrad/netcdf.py
konrad/surface.py

This PR:
* fixes the handling of `float` and `double` data types in netCDF
* adds documentation on why variables are stored as `float` and that they need to be converted into `double` when reading
* adds static pages for methods to the documentation

Fix data type handling when reading netCDF files

---

konrad/atmosphere.py

When creating an atmosphere from a netCDF file, data should be converted to double precision.  It is implemented for all variables except for pressure levels.
With this modification, restarts from past experiments now work as expected.

Atmosphere method `from_netcdf`: Added conversion to double precision also for pressure levels

---

.github/workflows/build-test.yml
README.md
setup.py

This PR:
* simplifies the installation for Python version for which CliMT does not provide binary wheels
* extends the description of the installation in the top-level README file

Simplify installation

---

konrad/core.py

It is problematic that the first time `RCE.run()` writes to the outputfile is after `self.writeevery` days and not in the beginning. I had some runs where the surface temperature strongly changed within the first day(s), which distorts the Gregoryplot, because in the netcdf file `surface['temperature'][0]` is not the surface temperature at the beginning of the simulation, but when the first value is written. The same is true for fluxes and can lead to an incorrect estimate for the effective forcing and total temperature change in scenarios with fast changes in the very beginning. The climate sensitivity parameter should be unaffected, because it only depends on the slope.
Writing out in the 1st time step solves this problem.
I can provide graphs for illustrating this if needed. So far it …

Make rce write to ouput file at 1st time step

---

konrad/radiation/arts.py

Store the ARTS lookup tables in a directory called "data". The former
name "aux" is a reserved name on Windows machines.

Change directory name from "aux" to "data"

---

konrad/humidity/relative_humidity.py

With the `ProfileFromData` class, one can give pressure and corresponding relative humidity arrays to be used as relative humidity profile through interpolation on the model's grid. 
This allow to reproduce for example a profile from another model output or reanalysis or observationnal data.

Add the possibility to define the RH profile from data

---

konrad/upwelling.py

This PR fixes the initialization of the `cooling_rates` variable in the `StratosphericUpwelling` class. In some cases - when the upwelling was never actually applied - the old implementation lead to crashes when attempting to write to netCDF.

Fix variable initialization

---

environment.yml
setup.py

The forked version loosens the dependency for NumPy which fixes the
installation on newer system and Python versions.

Replace CliMT dependency with our own fork

---

docs/source/index.rst
docs/source/konrad.entrainment.rst
konrad/__init__.py
konrad/convection.py
konrad/entrainment.py
konrad/netcdf.py
konrad/physics.py

This PR:
* changes the call interface of all `LapseRate` classes -> `lapse(p, T)`.
* revises the convective adjustment to properly integrate the temperate lapse-rate starting from the surface
* adds a conceptual model for entraining dry air masses (based on @jiaweibao implementation)
* fixes an issue when top-level variables in a class were not saved if netCDF subgroups have been defined

Revise convection

---

docs/source/konrad.convection.rst
docs/source/konrad.lapserate.rst
konrad/convection.py
konrad/lapserate.py

This PR:
* Replaces the former "fixed moist-adiabat" with an explicit lapse-rate cache.
```py
lapserate = konrad.lapserate.MoistLapseRate(fixed=True). # NO LONGER POSSIBLE
lapserate = konrad.lapserate.MoistLapseRate()
lapserate.build_cache(atmosphere)
```
* Lapse-rate classes return their values in pressure coordinates
* Add convenience class for dry-adiabatic lapse rate

Fix lapserate cache

---

setup.py

The PyPI does not allow pacakges to specify direct URLs anymore.

Replace direct URL of CliMT with  PyPI version

---

README.md
setup.py

This PR
* replaces the CliMT dependency with a version available on PyPI
* adds a description on how to retrieve said `climb` version on macOS

Fix setuptools

---

howto/atmosphere.md
howto/getting_started.md
howto/humidity.md
howto/lapserate.md
howto/netcdf_output.md
howto/surface.md

In addition to being more self-explaining, passing the surface
temperature as keyword argument also makes the call more robust for
older konrad versions.

Make the call of `FixedTemperature` more verbose

---

howto/lapserate.md

Pass a dry-adiabatic lapse rate component to the RCE object 
in the respective section instead of passing the lapse rate 
component created in the previous section

Use convenience class for dry-adiabatic lapse rate

---

konrad/humidity/relative_humidity.py

For class `VshapeT` implements a relative humidity (RH) profile that is
a constant function of temperature. This commit adds control parameters
so that the user can decided where the transition of the coldpoint and
boundary layer are located (in temperature space).

Add temperature controls to the V-shaped RH profile

---

konrad/radiation/rrtmg.py

The climate module may through import errors for non-compiled models (e.g. simple physics, Emanuel convection). This PR introduces a workaround to silence these warning that are created by a mix of `logging` and plain `print` statements.

Suppress all warnings during climt import

---

konrad/test/test_rce.py

This PR adds two test that check the actual integration of an RCE simulation. The simulation only runs for four time steps which should, however, be enough to capture most general issues.

Add an actual test of an RCE simulation

---

howto/atmosphere.md
howto/clouds.md
howto/convection.md
howto/feedback.md
howto/forcing.md
howto/getting_started.md
howto/humidity.md
howto/lapserate.md
howto/netcdf_output.md
howto/ozone.md
konrad/atmosphere.py
konrad/component.py
konrad/core.py
konrad/test/test_atmosphere.py
konrad/test/test_surface.py

This PR introduces a **breaking change** to the konrad API. Both the `atmosphere` and the `surface` that are passed as input to an `RCE` simulation are **copied** and no longer modified during the simulation.
This makes comparison to the initial state as well as running several consecutive model simulations cleaner.
Thos solves #224

Add deepcopy

---

konrad/aerosol.py
konrad/radiation/common.py

1. When we added the aerosol module, we forgot to add the zenodo link to download more aerosol profiles, I fixed this.
2. There was an error in the doc string for the fluxes2heating function, the pre-factor should be g/c_p, not F/c_p. In the code it's correct, only the docstring was wrong.

Small fixes
