konrad/convection.py
Set a default for convective timescale for the relaxed adjustment. Updated docstrings.
=> merge request: convection.py

konrad/humidity.py, konrad/utils.py, setup.py
Add minor fixes and preparations for upcoming release.
=> Preparation for release

konrad/__init__.py, konrad/atmosphere.py, konrad/component.py, konrad/convection.py, konrad/core.py, konrad/humidity.py, konrad/lapserate.py, konrad/netcdf.py, konrad/ozone.py, konrad/plots.py, konrad/radiation/psrad.py, konrad/radiation/radiation.py, konrad/radiation/rrtmg.py, konrad/surface.py, konrad/upwelling.py
PR summary:
* Introduce new class `Component` which is used as base class for all model components
* Replace all inheritance from `xarray.Dataset`
* Implement a `NetcdfHandler` to restore netCDF handling which has been handled by `xarray` before
=> Replace xarray

konrad/__init__.py, konrad/netcdf.py
Include information on model version and reference to netCDF file.
=> Extend netCDF output

konrad/atmosphere.py, konrad/cloud.py, konrad/humidity.py
This PR:
* Fixes the `Atmosphere.refine_plev()` method, which seems to have been broken
* Fix netCDF output of humidity classes that have the `vmr_profile` or `rh_profile` attribute set
=> Miscellaneous fixes

konrad/core.py, konrad/ozone.py, konrad/radiation/rrtmg.py
Sorry I made some stylist changes too, so it's a bit difficult to see the important changes!
=> Specify some cloud properties. Change calculation of convective top to use clear sky heating rates.

konrad/atmosphere.py, konrad/cloud.py, konrad/constants.py, konrad/convection.py, konrad/core.py, konrad/humidity.py, konrad/ozone.py
and use the convective heating rates!
=> Moved convective top calculation to convection class

konrad/atmosphere.py, konrad/cloud.py
Reopen the PR after major restructure of repository branches.
I will check the old PR #32 to sew which changes we agreed on.
=> Add simple `CloudEnsemble`

konrad/atmosphere.py, konrad/cloud.py, konrad/constants.py, konrad/convection.py
Fix MidLevelCloud and HighCloud cloud properties based on model levels.
Update LowCloud class.
=> Update cloud classes.

.travis.yml, README.md, konrad/test/test_atmosphere.py, setup.cfg, setup.py
This PR adds automated unit testing using [Travis CI](https://travis-ci.org)
=> Setup pytest and Travis CI

konrad/atmosphere.py, konrad/test/test_atmosphere.py
This PR introduces a new class constant ``pmin`` for the ``Atmosphere`` class. It is meant to make diagnostic methods more consistent.
=> Add pmin classconstant

konrad/__init__.py, konrad/humidity.py, konrad/lapserate.py, konrad/physics.py, setup.py
This PR:
* Adds a new ``physics`` submodule for consistent handling of physical functions.
* Changes the way relative humidity is defined. It is now defined using saturation with respect to water/ice depending on the actual atmospheric temperature.
* Bump required typhon version -> ``0.7.0``.
=> Revise relative humidity definition

konrad/humidity.py
This PR adds a draft version of a relative humidity model described in [Romps 2014](https://journals.ametsoc.org/doi/10.1175/JCLI-D-14-00255.1).
As is, the model is unstable for the default choices of solar constant (runaway greenhouse). A reduction of the solar constant by about 10 Wm^-2 allows stable simulations.
=> Add draft version of Romps (2014) humidity model.

konrad/constants.py, konrad/humidity/relative_humidity.py, konrad/physics.py
This PR:
* Fixes the calculation of the saturation pressure of water for the mixed-phase
* Sets new default parameters for most humidity models (mostly default surface RH)
=> Humidity component

konrad/atmosphere.py
The usage of accurate central differences has two benefits:
1. Results are returned on input grids (no offsetting)
2. Results should be numerically more stable
=> Use central differences to derive diagnostics

konrad/humidity/__init__.py, konrad/humidity/relative_humidity.py, konrad/humidity/stratosphere.py, konrad/plots.py, setup.py
I am sorry for the vacuous PR name, but there is no better way to describe this bunch of small commits... 🙈
=> Various changes

konrad/atmosphere.py, konrad/component.py, konrad/humidity/__init__.py, konrad/humidity/relative_humidity.py, konrad/humidity/stratosphere.py, konrad/netcdf.py, konrad/surface.py, konrad/utils.py
Among others this PR:
* Stores component's classnames in netCDF output
* Prohibits hashing of ``konrad.component.Component()``
* Enables hashing of component attributes
@SallyDa This PR got quite messy again, sorry. You don't have to review all changes, if you don't want to 😉
=> Revise inner workings

konrad/ozone.py
For the Cariolle scheme and Ed's simple chemistry scheme, apply the ozone transport everywhere, to get a smooth profile without jumps around the convective top.
Add a new ozone class, which uses Ed's simple chemistry scheme in the lower stratosphere, but merges to a specified ozone profile above this, avoiding problems with the unrealistic ozone destruction rates in the upper stratosphere of Ed's model.
=> Update ozone schemes

konrad/convection.py, konrad/core.py, konrad/test/test_convection.py
Even though it might look like I've changed a lot, I haven't. @lkluft, can we discuss further changes (inclusion of latent heat in energy conservation?) and testing?
=> Some convection improvements

konrad/cloud.py, konrad/convection.py, konrad/core.py, konrad/humidity/__init__.py, konrad/humidity/relative_humidity.py, konrad/humidity/stratosphere.py, konrad/lapserate.py, konrad/ozone.py, konrad/radiation/__init__.py, konrad/radiation/radiation.py, konrad/radiation/rrtmg.py, konrad/surface.py, konrad/upwelling.py
Add example usage to the docstring of some modules. Improve other docstrings and/or update formatting for sphinx.
=> Improve docs

konrad/surface.py
I've forgot that RRTMG needs the surface temperature to be a float and I've input it as an integer and got errors so many times. I don't know why I didn't make this pr ages ago...
=> Allow surface temperature input to be an integer

konrad/constants.py, konrad/upwelling.py
Include an option to fix the cooling term.
Include a 'realistic' upwelling velocity profile and couple it to the convective top.
=> Include more upwelling classes

konrad/lapserate.py
Use the log of the pressure, so that the interpolation is approx
linear with height.
=> Improve lapse rate interpolation

konrad/convection.py
to account for scenarios where the lower troposphere is cooled
by the convective adjustment, as sometimes happens when a diurnal
cycle is applied.
=> Update convective top index calculation

konrad/cloud.py, konrad/component.py, konrad/netcdf.py, konrad/radiation/rrtmg.py
This PR makes the ``Cloud`` class a subclass of ``Component``.
Currently, the netCDF file only includes the initial state of the cloud class as no ``time`` dimension is present. I will try to add this before my vacation.
=> Make clouds a model component

konrad/atmosphere.py, konrad/test/test_atmosphere.py
This PR fixes #104 and adds a test to check the ``Atmosphere.refine_plev`` interface in the future
=> Fix refine plev

konrad/surface.py
Use the lowest three atmosphere levels to perform a cubic extrapolation
for the surface temperature when initializing a surface from a given
atmosphere component.
The new approach should give the same results for linear temperature profiles and be more robust for moist adiabatic lapse rates at different temperature states.
=> Enhance creation of surface from given atmosphere

konrad/constants.py, konrad/core.py, konrad/netcdf.py, konrad/utils.py
This PR:
* Improves the internal time handling by using `datetime.datetime` and `datetime.timedelta` objects.
* Adds a `TimestepAdjuster` which allows the user to adjust the timestep during runtime.
=> Revise time handling

docs/source/conf.py, docs/source/konrad.cloud.rst, docs/source/konrad.humidity.rst, docs/source/konrad.ozone.rst, docs/source/konrad.surface.rst, konrad/cloud.py, konrad/convection.py, konrad/core.py, konrad/lapserate.py, konrad/ozone.py, konrad/radiation/__init__.py, konrad/surface.py, konrad/upwelling.py, konrad/utils.py
This PR:
* Adds missing objects to the documentation list (and removes outdated entries)
* Fixes syntax erros in docstrings to silence warnings
=> Fix documentation

docs/source/konrad.convection.rst, docs/source/konrad.humidity.rst, konrad/convection.py
Update convection & humidity doc files with new classes.
=> Update .srt files

docs/source/konrad.utils.rst, konrad/atmosphere.py, konrad/cloud.py, konrad/utils.py
This PR:
* implements the "fixed anvil temperature" (FAT) cloud coupling
* makes the coupling to the level of maximum clear-sky divergence (PHAT) more robust
* makes the variables `cloud_top_plev` and `cloud_top_temperature` time-dependent in order to write them into netCDF
=> Cloud coupling

konrad/radiation/arts.py
The new setup has a way broader temperature space to cover the cold
stratosphere in no-ozone simulations.
=> Revise setup for ARTS lookup table

konrad/radiation/arts.py
This PR
* adds a method to calculate optical thickness as function of wavenumber
* refactors the methods to set the atmospheric state within ARTS
=> Add method to calculate optical thickness

docs/source/konrad.humidity.rst, konrad/humidity/relative_humidity.py, konrad/lapserate.py, tutorials/simple_rce.ipynb
Reformatting the docstrings of PolynomialCshaped and ProfileFromData and some others
Fixing an error in the simple_rce tutorial
=> Reformat RH functions doc

docs/source/konrad.utils.rst, konrad/core.py, konrad/utils.py
This PR changes the default `RCE` configuration to use a fixed surface temperature. In addition, the maximum runtime and tilmestep are adjusted to reduce the model runtime.
=> Modify default

howto/_toc.yml, howto/convection.md, howto/forcing.md, howto/netcdf_output.md
This PR
* adds an example on how to disable the convection scheme
* shows how to restart from a stored model state
* adds plots to visualise the instantaneous and effective forcing
=> Extend "How to konrad"

konrad/ozone.py
The Cariolle ozone scheme does not really depend on the external
`simotrostra` package. We only used a conversion function for molecular
densities which is now implemented in-place.
However, the `simotrostra` package is still required for the same-named
ozone class.
=> Make the Cariolle scheme independent of `simotrostra`

howto/forcing.md
Also introduce the symbol used in plot labels.
=> Make description of radiative forcing more clear

konrad/utils.py
Thanks to @diegojco for reporting!
=> Fix typos in pressure grid formula

.github/workflows/build-test.yml, environment.yml, setup.py
This PR solves issues for the automated build with Python 3.9 that were caused by the dependency handling of CliMT.
=> Fix Python 3.9 build

konrad/atmosphere.py, konrad/radiation/arts.py
This PR
* replaces outdated calls to the typhon ARTS API with `pyarts`
* fixes calls to changed ARTS work space method
=> Fix ARTS interface

.github/workflows/build-book.yml, .github/workflows/build-test.yml, .github/workflows/python-publish.yml, README.md, environment.yml, konrad/test/test_rce.py, setup.py
This PR updates the build workflow, by:
* Updating the supported Python version to 3.9, 3.10, 3.11
* Using the lastet Ubuntu version
* Using a more recent GCC version in MacOS
* Updating used Github actions
=> Update build workflow

.github/workflows/build-test.yml
This PR adds the `workflow_dispatch` event to the test action to (hopefully) allow us to trigger it manually.
=> Allow manual actions

.github/workflows/build-book.yml, .github/workflows/build-test.yml, setup.cfg
This PR
* adds support for Python 3.11
* drops support for Python 3.8
=> Drop support for Python <3.9
